# Generated by Django 5.2.10 on 2026-04-21 22:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "-- Sélectionnez un service --"),
                            ("arbitrage", "01. Arbitrage & Médiation"),
                            ("audit", "02. Audit & Sécurité Juridique"),
                            ("creation", "03. Création de Sociétés & Contrats"),
                            ("representation", "04. Représentation & Intermédiation"),
                            ("contentieux", "05. Contentieux & Recouvrement"),
                            ("formation", "06. Formation & Coaching Stratégique"),
                            ("autre", "Autre demande"),
                        ],
                        max_length=50,
                        verbose_name="Service concerné",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "gdpr_consent",
                    models.BooleanField(
                        default=False, verbose_name="Consentement RGPD"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("read", "Lu"),
                            ("replied", "Répondu"),
                            ("archived", "Archivé"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LatinMaxim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latin_text",
                    models.CharField(max_length=200, verbose_name="Texte latin"),
                ),
                (
                    "french_translation",
                    models.CharField(
                        max_length=300, verbose_name="Traduction française"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Maxime latine",
                "verbose_name_plural": "Maximes latines",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Abonné newsletter",
                "verbose_name_plural": "Abonnés newsletter",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=2, verbose_name="Numéro")),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "icon_class",
                    models.CharField(
                        max_length=100, verbose_name="Classe icône (Lucide)"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(max_length=300, verbose_name="Description courte"),
                ),
                (
                    "full_description",
                    models.TextField(verbose_name="Description complète"),
                ),
                (
                    "color_class",
                    models.CharField(
                        default="blue", max_length=50, verbose_name="Couleur thème"
                    ),
                ),
                ("is_featured", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Service / Pôle d'expertise",
                "verbose_name_plural": "Services / Pôles d'expertise",
                "ordering": ["order", "number"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nom complet"),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Titre / Poste"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("founder", "Fondateur & Gérant"),
                            ("associate", "Associé"),
                            ("counsel", "Conseiller Juridique"),
                            ("assistant", "Assistant Juridique"),
                            ("staff", "Personnel"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField(verbose_name="Biographie")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_featured", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Membre de l'équipe",
                "verbose_name_plural": "Membres de l'équipe",
                "ordering": ["order", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("step_number", models.PositiveIntegerField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("droit-ohada", "Droit OHADA"),
                            ("immobilier", "Immobilier & Foncier"),
                            ("arbitrage", "Arbitrage & Médiation"),
                            ("fiscalite", "Fiscalité Côte d'Ivoire"),
                            ("actualites", "Actualités Juridiques"),
                            ("investissement", "Investissement en Afrique"),
                        ],
                        max_length=50,
                    ),
                ),
                ("excerpt", models.TextField(max_length=400, verbose_name="Résumé")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.teammember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de blog",
                "verbose_name_plural": "Articles de blog",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Nom du client"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Entreprise"
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=200, verbose_name="Poste"),
                ),
                ("content", models.TextField(verbose_name="Témoignage")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("is_featured", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
                "ordering": ["-created_at"],
            },
        ),
    ]
